StartupEvents.registry('item', event =>{
	event.create('basic_mechanism').displayName('Basic mechanism')
	event.create('incomplete_basic_mechanism').displayName('Incomplete basic mechanism')
	event.create('copper_mechanism').displayName('Copper mechanism')
	event.create('incomplete_copper_mechanism').displayName('Incomplete copper mechanism')
	event.create('steel_mechanism').displayName('Steel mechanism')
	event.create('incomplete_steel_mechanism').displayName('Incomplete steel mechanism')
	event.create('enchanted_mechanism').displayName('Enchanted mechanism')
	event.create('incomplete_enchanted_mechanism').displayName('Incomplete enchanted mechanism')
	event.create('conductive_mechanism').displayName('Conductive mechanism')
	event.create('incomplete_conductive_mechanism').displayName('Incomplete conductive mechanism')
	event.create('mystical_mechanism').displayName('Mystical mechanism')
	event.create('incomplete_mystical_mechanism').displayName('Incomplete mystical mechanism')
	event.create('simulated_base').displayName('Simulated base')
	event.create('simulated_mechanism').displayName('Simulated mechanism')
	event.create('incomplete_basic_control_circuit').displayName('Incomplete control circuit')
	event.create('mek_mechanism').displayName('Mek mechanism')
	event.create('mek_base').displayName('Mek base')
	event.create('superseed').displayName('Super semilla')
	event.create('alma').displayName('Alma de dragon')
	event.create('antimateria').displayName('Antimateria')
	event.create('blackhole').displayName('BlackHole')
	event.create('brujulamaldita').displayName('Brujula maldita')
	event.create('calavera').displayName('Calavera')
	event.create('catalizadordeoblivion').displayName('Catalizador de Oblivion')
	event.create('combustible').displayName('Combustible')
	event.create('doll').displayName('Muneco de paja')
	event.create('easteregg').displayName('Easter egg')
	event.create('emeraldcoin').displayName('Moneda de esmeralda')
	event.create('ironcoin').displayName('Moneda de hierro')
	event.create('lingotedeacero').displayName('Lingote de acero')
	event.create('miniportal').displayName('Mini portal')
	event.create('minireactor').displayName('Mini reactor')
	event.create('moneda_de_oro').displayName('Moneda de oro')
	event.create('netheritecoin').displayName('Moneda de netherite')
	event.create('patricio').displayName('Patricio')
	event.create('planos').displayName('Planos')
	event.create('semilla').displayName('Semilla')
	event.create('star').displayName('Mega estrella')
	event.create('starnugget').displayName('Fragmentos de mega estrella')
	event.create('transmisor').displayName('Transmisor')
	event.create('universal_press').texture('kubejs:item/universal_press').maxStackSize(64).displayName('Universal Press');
})

