JEIEvents.hideItems(event => {
  event.hide(['angelring:leadstone_angel_ring', 'angelring:hardened_angel_ring', 'angelring:reinforced_angel_ring', 'angelring:resonant_angel_ring'])
  event.hide('reliquary:rod_of_lyssa')
  event.hide('mekanism:upgrade_anchor')
  event.hide('ars_nouveau:glyph_animate_block')
  event.hide(/generatorgalore:.*_upgrade/)


  //desabilitado
  event.hide([
    'thermal:dynamo_disenchantment',
    'industrialforegoing:mycelial_disenchantment',
    'industrialforegoing:enchantment_sorter',
    'industrialforegoing:enchantment_extractor',
    'industrialforegoing:enchantment_factory',
    'reliquary:magicbane',
    'industrialforegoing:hydroponic_bed',
    'apotheosis:ender_library',
    'reliquary:holy_hand_grenade',
    'thermal:ender_grenade',
    'thermal:ice_grenade',
    'thermal:lightning_grenade',
    'thermal:redstone_grenade',
    'thermal:explosive_grenade',
    'thermal:earth_grenade',
    'thermal:nuke_grenade',
    'thermal:phyto_tnt',
    'thermal:fire_grenade',
    'thermal:glowstone_grenade',
    'thermal:slime_grenade',
    'apotheosis:gem',
    'avaritia:singularity',
    'avaritia:compressed_crafting_table',
    'avaritia:double_compressed_crafting_table',
    'avaritia:neutron_compressor',
    'avaritia:extreme_crafting_table',
    'extendedcrafting:ultimate_singularity',
    'allthemodium:vibranium_hoe',
    'allthemodium:vibranium_hoe',
    'cataclysm:tidal_claws',
    'allthemodium:vibranium_axe',
    'allthemodium:vibranium_pickaxe',
    'allthemodium:vibranium_sword',
    'allthemodium:unobtainium_hoe',
    'allthemodium:unobtainium_shovel',
    'allthemodium:unobtainium_axe',
    'allthemodium:unobtainium_pickaxe',
    'allthemodium:unobtainium_sword',
    'allthemodium:vibranium_chestplate',
    'allthemodium:vibranium_leggings',
    'allthemodium:unobtainium_chestplate',
    'allthemodium:unobtainium_helmet',
    'allthemodium:unobtainium_leggings',
    'allthemodium:unobtainium_boots',
    'allthemodium:vibranium_helmet',
    'allthemodium:vibranium_boots',
    'mob_grinding_utils:ender_inhibitor_off',
    'betterfurnacesreforged:diamond_upgrade',
    'betterfurnacesreforged:extreme_upgrade',
    'industrialforegoing:animal_baby_separator',
    'industrialforegoing:animal_rancher',
    'industrialforegoing:animal_feeder',
    'betterfurnacesreforged:gold_upgrade',
    'betterfurnacesreforged:netherhot_upgrade',
    'thermal:fluid_cell',
    'farmingforblockheads:feeding_trough',
    'create:handheld_worldshaper',
    'thermal:energy_cell',
    'betterfurnacesreforged:iron_upgrade',
    'allthemodium:teleport_pad',
    'expandedstorage:copper_to_iron_conversion_kit',
    'expandedstorage:wood_to_netherite_conversion_kit',
    'expandedstorage:wood_to_obsidian_conversion_kit',
    'expandedstorage:diamond_to_obsidian_conversion_kit',
    'expandedstorage:netherite_chest',
    'mekanism:personal_chest',
    'avaritia:iron_singularity',
    'avaritia:golden_singularity',
    'avaritia:lapis_singularity',
    'avaritia:redstone_singularity',
    'avaritia:redstone_singularity',
    'avaritia:diamond_singularity',
    'avaritia:emerald_singularity',
    'avaritia:netherite_singularity',
    'avaritia:extreme_crafting_table',
    'avaritia:copper_singularity',
    'avaritia:amethyst_singularity',
    'avaritia:double_compressed_crafting_table',
    'avaritia:compressed_crafting_table',
    'avaritia:neutronium_compressor',
    'reliquary:magicbane', 
    'allthemodium:vibranium_hoe',
    'allthemodium:vibranium_hoe',
    'allthemodium:vibranium_axe',
    'allthemodium:vibranium_pickaxe',
    'allthemodium:vibranium_sword',
    'allthemodium:unobtainium_hoe',
    'allthemodium:unobtainium_shovel',
    'allthemodium:unobtainium_axe',
    'allthemodium:unobtainium_pickaxe',
    'allthemodium:unobtainium_sword',
    'allthemodium:vibranium_chestplate',
    'allthemodium:vibranium_leggings',
    'allthemodium:unobtainium_chestplate',
    'allthemodium:unobtainium_helmet',
    'allthemodium:unobtainium_leggings',
    'allthemodium:unobtainium_boots',
    'reliquary:magicbane',
    'apotheosis:gem',
    'industrialforegoing:hydroponic_bed',
    'angelring:resonant_angel_ring',
    'expandedstorage:diamond_to_netherite_conversion_kit',
    'expandedstorage:gold_to_diamond_conversion_kit',
    'expandedstorage:wood_to_iron_conversion_kit',
    'expandedstorage:wood_to_diamond_conversion_kit',
    'expandedstorage:wood_to_gold_conversion_kit',
    'expandedstorage:copper_to_netherite_conversion_kit',
    'expandedstorage:copper_to_diamond_conversion_kit',
    'expandedstorage:iron_to_diamond_conversion_kit',
    'expandedstorage:copper_to_gold_conversion_kit',
    'expandedstorage:obsidian_to_netherite_conversion_kit', 
    'expandedstorage:wood_to_copper_conversion_kit',
    'expandedstorage:gold_to_netherite_conversion_kit',
    'expandedstorage:iron_to_netherite_conversion_kit',
    'expandedstorage:gold_to_obsidian_conversion_kit',
    'expandedstorage:iron_to_obsidian_conversion_kit',
    'expandedstorage:iron_to_gold_conversion_kit',
    'expandedstorage:copper_to_obsidian_conversion_kit',
    'expandedstorage:netherite_chest_minecart',
    'expandedstorage:obsidian_chest_minecart',
    'mekanism:personal_barrel',
    'expandedstorage:present_minecart',
    'alltheores:iron_ore_hammer',
    'apotheosis:simple_reforging_table',
    'expandedstorage:pumpkin_chest',
    'expandedstorage:waxed_exposed_copper_mini_barrel',
    'apotheosis:vial_of_unnaming',
    Item.of('alltheores:copper_ore_hammer', '{Damage:0}'),
    Item.of('alltheores:invar_ore_hammer', '{Damage:0}'),
    'expandedstorage:pumpkin_chest_minecart',
    'apotheosis:vial_of_extraction',
    'apotheosis:vial_of_expulsion',
    'ftbquests:stage_barrier',
    'expandedstorage:diamond_chest_minecart',
    'expandedstorage:diamond_mini_chest',
   'expandedstorage:gold_chest_minecart',
   'expandedstorage:exposed_copper_mini_barrel',
   'expandedstorage:wood_chest_minecart',
   'mob_grinding_utils:gm_chicken_feed',
   'ftbquests:barrier',
   Item.of('expandedstorage:netherite_mini_barrel', '{BlockStateTag:{sparrow:"true"}}'),
   'expandedstorage:moss_chest_minecart',
   'expandedstorage:iron_chest_minecart',
   Item.of('alltheores:bronze_ore_hammer', '{Damage:0}'),
   'expandedstorage:white_mini_present',
   'expandedstorage:gold_chest',
   'expandedstorage:mini_barrel'
    
  ])

   //baneado
   event.hide([
    Item.of('minecraft:tipped_arrow', '{Potion:"alexscaves:magnetizing"}'),
    Item.of('minecraft:tipped_arrow', '{Potion:"alexscaves:long_magnetizing"}'),
    Item.of('minecraft:potion', '{Potion:"alexscaves:magnetizing"}'),
    Item.of('minecraft:potion', '{Potion:"alexscaves:long_magnetizing"}'),
    Item.of('minecraft:splash_potion', '{Potion:"alexscaves:long_magnetizing"}'),
    Item.of('minecraft:lingering_potion', '{Potion:"alexscaves:magnetizing"}'),
    Item.of('minecraft:lingering_potion', '{Potion:"alexscaves:long_magnetizing"}'),
    Item.of('minecraft:splash_potion', '{Potion:"alexscaves:magnetizing"}'),
    'pedestals:upgrade_pedestal_magnet',
    'ae2wtlib:magnet_card',
    'mekanismadditions:obsidian_tnt',
    'ae2:tiny_tnt',
    'minecraft:tnt',
    'minecraft:tnt_minecart',
    'thermal:fire_tnt',
    'thermal:ice_tnt',
    'thermal:lightning_tnt',
    'thermal:earth_tnt',
    'thermal:ender_tnt',
    'thermal:redstone_tnt',
    'thermal:slime_tnt',
    'mekanism:module_blasting_unit',
    'thermal:glowstone_tnt',
    'thermal:nuke_tnt',
    'gag:fishing_dynamite',
    'gag:mining_dynamite',
   ])






  if (global.chunk) {
    event.hide('mekanism:dimensional_stabilizer')
    event.hide('ae2:spatial_anchor')
  }
})


const $CreatingFluxRecipe = Java.loadClass('sonar.fluxnetworks.client.jei.CreatingFluxRecipe')
const $CreatingFluxRecipeCategory = Java.loadClass('sonar.fluxnetworks.client.jei.CreatingFluxRecipeCategory')

JEIEvents.addItems(event => {
  let RecipeManager = global.jeiRuntime.getRecipeManager()
  let customFlux = new $CreatingFluxRecipe('minecraft:crying_obsidian', 'minecraft:obsidian', 'minecraft:redstone', 'fluxnetworks:flux_dust')
  RecipeManager.addRecipes($CreatingFluxRecipeCategory.RECIPE_TYPE, [customFlux])
})